config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {sign_in: "login", sign_out: 'logout', sign_up: 'register'}
  resources :portfolio_sets, except: [:show]
  get 'portfolio/:id', to: 'portfolio_sets#show', as: 'portfolio_show'
  get 'vuejs-items', to: 'portfolio_sets#vuejs'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :blogs do
  	member do
  		get :toggle_status
  	end
  end


  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body
  belongs_to :topic
end

app/models/concerns/placeholder.rb
module Placeholder
  extend ActiveSupport::Concern

  def self.image_generator(height:, width:)
    "https://picsum.photos/#{height}/#{width}"
  end
end

app/models/portfolio_set.rb
class PortfolioSet < ApplicationRecord
  include Placeholder

  extend FriendlyId
  friendly_id :title, use: :slugged
  has_many :technologies
  accepts_nested_attributes_for :technologies,
                                reject_if: ->(attrs) { attrs['name'].blank? }

  validates_presence_of :title, :body, :main_image, :thumb_image

  def self.vuejs
    where(subtitle: 'Vuejs')
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: 'Ruby on Rails') }

  after_initialize :set_defaults

  def set_defaults
    self.main_image ||= Placeholder.image_generator(height: '400', width: '600')
    self.thumb_image ||= Placeholder.image_generator(height: '350', width: '150')
  end
end

app/models/skill.rb
class Skill < ApplicationRecord
  include Placeholder
  validates_presence_of :title, :percent_utilized

  after_initialize :set_defaults

  def set_defaults
    self.badge ||= Placeholder.image_generator(height: '250', width: '250')
  end
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :portfolio_set
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :blog
  validates_presence_of :title
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :name

  def first_name
    name.split.first
  end

  def last_name
    name.split.last
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include DeviseWhitelist
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy toggle_status]

  def index
    @blogs = Blog.all
  end

  def show; end

  def new
    @blog = Blog.new
  end

  def edit; end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft?

    end
    redirect_to blogs_url, notice: 'Post status has changed'
  end

  private

  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/controllers/concerns/devise_whitelist.rb
module DeviseWhitelist
  extend ActiveSupport::Concern
  included do
    before_action :configure_permitted_parameters, if: :devise_controller?
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @posts = Blog.all
    @skills = Skill.all
  end

  def about; end

  def contact; end
end

app/controllers/portfolio_sets_controller.rb
class PortfolioSetsController < ApplicationController
  def index
    @portfolio_items = PortfolioSet.all
  end

  def vuejs
    @vuejs_portfolio_items = PortfolioSet.vuejs
  end

  def ruby_on_rails
    @ruby_on_rails_items = PortfolioSet.ruby_on_rails_portfolio_items
  end

  def new
    @portfolio_item = PortfolioSet.new
    3.times { @portfolio_item.technologies.build }
  end

  def create
    @portfolio_item = PortfolioSet.new(params.require(:portfolio_set).permit(:title, :subtitle, :body,
                                                                             technologies_attributes: [:name]))

    if @portfolio_item.save
      redirect_to portfolio_sets_path
    else
      render :new
    end
  end

  def show
    @portfolio_item = PortfolioSet.friendly.find(params[:id])
  end

  def edit
    @portfolio_item = PortfolioSet.friendly.find(params[:id])
  end

  def update
    @portfolio_item = PortfolioSet.friendly.find(params[:id])
    if @portfolio_item.update(params.require(:portfolio_set).permit(:title, :subtitle, :body, :main_image,
                                                                    :thumb_image))
      redirect_to portfolio_sets_path
    else
      render :edit
    end
  end

  def destroy
    @portfolio_item = PortfolioSet.friendly.find(params[:id])
    @portfolio_item.destroy

    redirect_to portfolio_sets_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/portfolio_sets_helper.rb
module PortfolioSetsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
        <% blog.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blogs</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @blogs.each do |blog| %>
      <tr>
        <td><%= blog.title %></td>
        <td><%= blog.body %></td>
        <td><%= link_to blog.status, toggle_status_blog_path(blog)  %></td>
        <td><%= link_to 'Show', blog %></td>
        <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
        <td><%= link_to 'Destroy', blog, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blog', new_blog_path %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if current_user %>
    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
    <% else %>
    <%= link_to 'Register', new_user_registration_path %>
    <%= link_to 'Login', new_user_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Hi, <%= current_user.first_name if current_user %></h1>


<h2>Blog posts</h2>
<% @posts.each do |post|%>
<li><div><%= post.title %></div> <div><%= post.body %></div></li>
<% end %>


<h2>Skills</h2>
<% @skills.each do |skill|%>
<li><div><%= skill.title %></div> <div><%= skill.percent_utilized %></div></li>
<% end %>

app/views/portfolio_sets/edit.html.erb
<h1>Edit PortfolioSet Item</h1>


<%= form_with(model: @portfolio_item) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
   <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :main_image %>
    <%= form.text_area :main_image %>
  </div>
  <div class="field">
    <%= form.label :thumb_image %>
    <%= form.text_area :thumb_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', portfolio_sets_path %>

app/views/portfolio_sets/index.html.erb
<h1>Portfolio items</h1>

<%= link_to 'New Portfolio Set', new_portfolio_set_path %> <br>

<%= new_portfolio_set_path %> <br>
<%= new_portfolio_set_url %> <br>
<% @portfolio_items.each do |item| %>
	<div><%= link_to item.title, portfolio_show_path(item) %></div>
	<div><%= item.subtitle %></div>
	<div><%= item.body %></div>
	<div><%= image_tag item.thumb_image %></div>
	<%= link_to 'Edit', edit_portfolio_set_path(item) %>
	<%= link_to 'Delete Portfolio Item', portfolio_set_path(item), method: :delete, data: {confirm: 'Are you sure?' } %>
	<hr>
<%end%>

app/views/portfolio_sets/new.html.erb
<h1>Create a new PortfolioSet Item</h1>


<%= form_with(model: @portfolio_item) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
   <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <ul>
    <%= form.fields_for :technologies do |trchnology_form| %>
    <li>
      <%= trchnology_form.label :name %>
      <%= trchnology_form.text_field :name %>
      
    </li>
    <% end %>
  </ul>

  <div class="field">
    <%= form.label :main_image %>
    <%= form.text_area :main_image %>
  </div>
  <div class="field">
    <%= form.label :thumb_image %>
    <%= form.text_area :thumb_image %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Back', portfolio_sets_path %>

app/views/portfolio_sets/show.html.erb
<h1>Portfolio Set Show</h1>

<div>
	<%= image_tag @portfolio_item.main_image unless @portfolio_item.main_image.nil? %>
</div>

<h2><%= @portfolio_item.title %></h2>
<h3><%= @portfolio_item.subtitle %></h3>

<p><%= @portfolio_item.body%></p>

<%= link_to 'Edit', edit_portfolio_set_path(@portfolio_item) %>

<%= link_to 'Back', portfolio_sets_path %>

<h2>Technologies used</h2>

<% @portfolio_item.technologies.each do |t| %>
<p> <%= t.name %></p>
<% end %>

app/views/portfolio_sets/vuejs.html.erb
<h1>Vuejs Portfolio items</h1>

<%= link_to 'New Portfolio Set', new_portfolio_set_path %> <br>

<%= new_portfolio_set_path %> <br>
<%= new_portfolio_set_url %> <br>
<% @vuejs_portfolio_items.each do |item| %>
	<div><%= link_to item.title, portfolio_show_path(item) %></div>
	<div><%= item.subtitle %></div>
	<div><%= item.body %></div>
	<div><%= image_tag item.thumb_image %></div>
	<%= link_to 'Edit', edit_portfolio_set_path(item) %>
	<%= link_to 'Delete Portfolio Item', portfolio_set_path(item), method: :delete, data: {confirm: 'Are you sure?' } %>
	<hr>
<%end%>